'use client'

import { useState, useEffect, useCallback, useRef } from 'react'
import type { RawArticle } from '@/lib/semi-newsapi'
import type { CategorizedArticle, Analysis } from '@/lib/semi-intelligence'

type Timeframe = '1d' | '1w' | '1m' | '3m' | '1y'
type Mode = 'industry' | 'policy' | 'investment'
type Phase = 'idle' | 'loading' | 'done' | 'error'

const TIMEFRAME_LABELS: Record<Timeframe, string> = {
  '1d': '24H',
  '1w': '7D',
  '1m': '1M',
  '3m': '3M',
  '1y': '1Y',
}

const MODE_LABELS: Record<Mode, string> = {
  industry: 'Industry',
  policy: 'Policy & Trade',
  investment: 'Investment',
}

const MODE_DESCRIPTION: Record<Mode, string> = {
  industry: 'Company news, technology breakthroughs, fab capacity, and supply chain developments',
  policy: 'Export controls, sanctions, trade restrictions, and geopolitical developments',
  investment: 'Funding rounds, M&A deals, IPOs, and capital flows in the semiconductor sector',
}

function timeAgo(dateString: string): string {
  const diff = Date.now() - new Date(dateString).getTime()
  const mins = Math.floor(diff / 60000)
  const hours = Math.floor(mins / 60)
  const days = Math.floor(hours / 24)
  if (mins < 60) return `${mins}m ago`
  if (hours < 24) return `${hours}h ago`
  if (days < 7) return `${days}d ago`
  return new Date(dateString).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
}

function Divider() {
  return <div className="border-t border-white/20" />
}

function ArticleRow({ article }: { article: CategorizedArticle }) {
  return (
    <div className="py-4">
      <a
        href={article.url}
        target="_blank"
        rel="noopener noreferrer"
        className="text-sm font-semibold leading-snug hover:underline text-white"
      >
        {article.title}
      </a>
      <div className="mt-0.5 text-xs text-gray-500 uppercase tracking-wide">
        {article.source?.name} &middot; {timeAgo(article.publishedAt)}
      </div>
      <div className="mt-1.5 text-sm text-gray-400">
        &rarr; {article.insight}
      </div>
    </div>
  )
}

function ArticleSection({
  label,
  articles,
  empty,
}: {
  label: string
  articles: CategorizedArticle[]
  empty: string
}) {
  return (
    <section>
      <Divider />
      <div className="flex items-baseline justify-between py-2">
        <span className="text-xs font-bold uppercase tracking-widest text-white">{label}</span>
        <span className="text-xs text-gray-500">{articles.length}</span>
      </div>
      <Divider />
      {articles.length === 0 ? (
        <p className="py-4 text-sm text-gray-500">{empty}</p>
      ) : (
        <div className="divide-y divide-white/10">
          {articles.map((a) => (
            <ArticleRow key={a.url} article={a} />
          ))}
        </div>
      )}
    </section>
  )
}

function AnalysisSection({ analysis }: { analysis: Analysis }) {
  return (
    <section>
      <Divider />
      <div className="py-2">
        <span className="text-xs font-bold uppercase tracking-widest text-white">Strategic Analysis</span>
      </div>
      <Divider />
      <div className="py-4 space-y-5">
        <p className="text-sm leading-relaxed text-gray-200">{analysis.summary}</p>
        <div>
          <p className="text-xs font-bold uppercase tracking-widest text-gray-500 mb-2">
            What to Watch
          </p>
          <ol className="space-y-2">
            {analysis.adjustments.map((adj, i) => (
              <li key={i} className="flex gap-3 text-sm">
                <span className="text-gray-600 select-none font-mono text-xs pt-0.5">
                  {String(i + 1).padStart(2, '0')}
                </span>
                <span className="leading-relaxed text-gray-300">{adj}</span>
              </li>
            ))}
          </ol>
        </div>
      </div>
    </section>
  )
}

type TabState = {
  phase: Phase
  needToKnow: CategorizedArticle[]
  strategyAltering: CategorizedArticle[]
  analysis: Analysis | null
  articles: RawArticle[]
  lastUpdated: Date | null
  error: string | null
}

const INITIAL_TAB_STATE: TabState = {
  phase: 'idle',
  needToKnow: [],
  strategyAltering: [],
  analysis: null,
  articles: [],
  lastUpdated: null,
  error: null,
}

export default function IntelligencePage() {
  const [activeMode, setActiveMode] = useState<Mode>('industry')
  const [timeframe, setTimeframe] = useState<Timeframe>('1w')
  const [tabState, setTabState] = useState<Record<Mode, TabState>>({
    industry: { ...INITIAL_TAB_STATE },
    policy: { ...INITIAL_TAB_STATE },
    investment: { ...INITIAL_TAB_STATE },
  })
  const autoRefreshRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const hasAutoGenerated = useRef(false)

  const current = tabState[activeMode]
  const isLoading = current.phase === 'loading'

  const generate = useCallback(
    async (tf: Timeframe = timeframe, mode: Mode = activeMode) => {
      setTabState((prev) => ({
        ...prev,
        [mode]: { ...prev[mode], phase: 'loading', error: null },
      }))

      try {
        const res = await fetch('/api/intelligence', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ timeframe: tf, mode }),
        })
        const data = await res.json()
        if (!res.ok) throw new Error(data.error ?? 'Generation failed')

        const { articles, needToKnow, strategyAltering, analysis } = data
        setTabState((prev) => ({
          ...prev,
          [mode]: {
            phase: 'done',
            needToKnow,
            strategyAltering,
            analysis,
            articles,
            lastUpdated: new Date(),
            error: null,
          },
        }))
      } catch (err) {
        setTabState((prev) => ({
          ...prev,
          [mode]: {
            ...prev[mode],
            phase: 'error',
            error: err instanceof Error ? err.message : 'Something went wrong.',
          },
        }))
      }
    },
    [timeframe, activeMode]
  )

  // Auto-generate all tabs on first load
  useEffect(() => {
    if (hasAutoGenerated.current) return
    hasAutoGenerated.current = true
    ;(['industry', 'policy', 'investment'] as Mode[]).forEach((mode) =>
      generate(timeframe, mode)
    )
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const handleTimeframeChange = (tf: Timeframe) => {
    setTimeframe(tf)
    if (current.phase === 'done' || current.phase === 'error') {
      generate(tf, activeMode)
    }
  }

  useEffect(() => {
    if (autoRefreshRef.current) clearInterval(autoRefreshRef.current)
    autoRefreshRef.current = setInterval(() => {
      if (current.phase === 'done') generate()
    }, 4 * 60 * 60 * 1000)
    return () => {
      if (autoRefreshRef.current) clearInterval(autoRefreshRef.current)
    }
  }, [current.phase, generate])

  const statusText =
    isLoading
      ? 'Pulling sources and analyzing...'
      : current.lastUpdated
      ? `Updated ${timeAgo(current.lastUpdated.toISOString())}`
      : null

  const today = new Date().toLocaleDateString('en-US', {
    weekday: 'short',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })

  return (
    <div className="min-h-screen bg-black text-white">
      <div className="max-w-7xl mx-auto px-6 py-10">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-xl font-bold tracking-tight">Daily Briefing</h1>
          <p className="text-xs text-gray-500 mt-0.5">{today}</p>
        </div>

        {/* Tabs */}
        <div className="flex gap-0 mb-6 border-b border-white/20">
          {(['industry', 'policy', 'investment'] as Mode[]).map((mode) => (
            <button
              key={mode}
              onClick={() => setActiveMode(mode)}
              className={`px-4 py-2 text-xs font-bold uppercase tracking-widest transition-colors ${
                activeMode === mode
                  ? 'border-b-2 border-white -mb-px text-white'
                  : 'text-gray-500 hover:text-white'
              }`}
            >
              {MODE_LABELS[mode]}
            </button>
          ))}
        </div>

        {/* Controls */}
        <div className="flex flex-wrap items-center gap-4 mb-6">
          <div className="flex gap-1">
            {(Object.keys(TIMEFRAME_LABELS) as Timeframe[]).map((tf) => (
              <button
                key={tf}
                onClick={() => handleTimeframeChange(tf)}
                disabled={isLoading}
                className={`px-2.5 py-1 text-xs font-mono transition-colors ${
                  timeframe === tf
                    ? 'bg-white text-black'
                    : 'text-gray-500 hover:text-white disabled:opacity-40'
                }`}
              >
                {TIMEFRAME_LABELS[tf]}
              </button>
            ))}
          </div>

          <div className="flex gap-3 ml-auto items-center">
            <button
              onClick={() => generate()}
              disabled={isLoading}
              className="text-xs font-bold uppercase tracking-widest border border-white/40 px-3 py-1.5 hover:bg-white hover:text-black transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
            >
              {isLoading ? 'Generating...' : current.phase === 'idle' ? 'Generate' : 'Refresh'}
            </button>
          </div>
        </div>

        {/* Status */}
        {statusText && (
          <p className="text-xs text-gray-500 mb-6">{statusText}</p>
        )}

        {/* Idle state */}
        {current.phase === 'idle' && (
          <div className="border border-dashed border-white/10 py-16 text-center">
            <p className="text-sm text-gray-400">Select a time frame and click Generate</p>
            <p className="text-xs text-gray-600 mt-1">{MODE_DESCRIPTION[activeMode]}</p>
          </div>
        )}

        {/* Error state */}
        {current.phase === 'error' && current.error && (
          <div className="border border-white/20 p-4 mb-6">
            <p className="text-xs font-bold uppercase tracking-widest mb-1">Error</p>
            <p className="text-sm text-gray-400">{current.error}</p>
            <button
              onClick={() => generate()}
              className="mt-3 text-xs underline hover:no-underline text-gray-300"
            >
              Try again
            </button>
          </div>
        )}

        {/* Loading skeleton */}
        {isLoading && !current.analysis && (
          <div className="space-y-8 animate-pulse">
            {[0, 1].map((i) => (
              <div key={i}>
                <div className="h-px bg-white/20 mb-2" />
                <div className="h-3 w-24 bg-white/10 mb-2" />
                <div className="h-px bg-white/20 mb-4" />
                {[0, 1, 2].map((j) => (
                  <div key={j} className="py-4 border-b border-white/10">
                    <div className="h-3 bg-white/10 w-3/4 mb-2" />
                    <div className="h-2 bg-white/5 w-1/4 mb-2" />
                    <div className="h-2 bg-white/5 w-2/3" />
                  </div>
                ))}
              </div>
            ))}
          </div>
        )}

        {/* Content */}
        {current.phase === 'done' && current.analysis && (
          <div className="space-y-8">
            {current.analysis && (
              <AnalysisSection analysis={current.analysis} />
            )}
            <ArticleSection
              label="Need to Know"
              articles={current.needToKnow}
              empty="No major discrete events this period."
            />
            <ArticleSection
              label="Signals"
              articles={current.strategyAltering}
              empty="No directional signals this period."
            />
            <Divider />
          </div>
        )}
      </div>
    </div>
  )
}
