import { NextRequest, NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { claude } from "@/lib/claude"

export async function GET() {
  const newsletters = await prisma.newsletter.findMany({
    orderBy: { createdAt: "desc" },
  })
  return NextResponse.json(newsletters)
}

export async function POST(req: NextRequest) {
  const body = await req.json()

  const twoWeeksAgo = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000)
  const recentArticles = await prisma.newsArticle.findMany({
    where: { scrapedAt: { gte: twoWeeksAgo } },
    orderBy: { scrapedAt: "desc" },
    take: 30,
  })

  const top100 = await prisma.company.findMany({
    where: { isTop100: true },
    orderBy: { top100Rank: "asc" },
    take: 10,
    include: { category: true },
  })

  const now = new Date()
  const period = `${now.getFullYear()}-W${Math.ceil(now.getDate() / 7).toString().padStart(2, "0")}`

  let content: string
  try {
    content = await generateWithClaude(recentArticles, top100, period)
  } catch {
    content = generateFallbackMarkdown(recentArticles, top100, period)
  }

  const newsletter = await prisma.newsletter.create({
    data: {
      title: body.title ?? `China Semiconductor Digest — ${period}`,
      content,
      period,
      status: "draft",
    },
  })

  return NextResponse.json(newsletter, { status: 201 })
}

async function generateWithClaude(articles: any[], top100: any[], period: string): Promise<string> {
  const articleSummaries = articles.slice(0, 20).map((a, i) =>
    `${i + 1}. [${a.source}] ${a.title}${a.summary ? `\n   Summary: ${a.summary}` : ""}\n   URL: ${a.url}`
  ).join("\n\n")

  const companyList = top100.slice(0, 10).map(c =>
    `#${c.top100Rank} ${c.nameEn} (${c.nameZhSimplified ?? "—"}) — ${c.category?.name ?? "Uncategorized"}`
  ).join("\n")

  const prompt = `You are writing a bi-weekly intelligence digest for professionals tracking China's semiconductor industry. Based on the following scraped news articles and company data, write a polished editorial newsletter in Markdown.

Period: ${period}

## Recent News Articles
${articleSummaries || "No recent articles available."}

## Top Ranked Companies This Period
${companyList || "No ranked companies available."}

Write the newsletter with these sections:
1. **Executive Summary** — 2-3 sentences on the most significant theme or story this fortnight
2. **Key Developments** — 3-5 bullet points of the most important stories with brief analysis (1-2 sentences each)
3. **Company Watch** — Brief notes on any notable activity from top-ranked companies mentioned in the news
4. **What to Watch** — 2-3 forward-looking items or trends to monitor

Keep the tone professional and analytical. Cite article sources inline. Write for an audience of investors, policy analysts, and industry professionals.`

  const stream = claude.messages.stream({
    model: "claude-opus-4-7",
    max_tokens: 2000,
    thinking: { type: "adaptive" },
    messages: [{ role: "user", content: prompt }],
  })

  const response = await stream.finalMessage()
  const textBlock = response.content.find(b => b.type === "text")
  return textBlock ? (textBlock as any).text : generateFallbackMarkdown(articles, top100, period)
}

function generateFallbackMarkdown(articles: any[], top100: any[], period: string): string {
  const articleSection = articles.length > 0
    ? articles.slice(0, 15).map(a =>
        `### ${a.title}\n*${a.source} · ${a.publishedAt?.toLocaleDateString() ?? "—"}*\n\n${a.summary ?? ""}\n\n[Read more](${a.url})`
      ).join("\n\n---\n\n")
    : "*No news articles scraped yet.*"

  const companySection = top100.length > 0
    ? top100.slice(0, 5).map(c =>
        `**#${c.top100Rank} ${c.nameEn}** (${c.nameZhSimplified ?? "—"}) — ${c.category?.name ?? "Uncategorized"}`
      ).join("\n")
    : "*No companies ranked yet.*"

  return `# China Semiconductor Intelligence — ${period}\n\n## This Fortnight in Chinese Semiconductors\n\n${articleSection}\n\n---\n\n## Spotlight: Top Ranked Companies\n\n${companySection}\n\n---\n\n*Generated by China Semiconductor Intelligence Dashboard*\n`
}
